export const COUNTRIES = [
    { label: 'Afghanistan', value: 'AF' },
    { label: 'Albania', value: 'AL' },
    { label: 'Algeria', value: 'DZ' },
    { label: 'Andorra', value: 'AD' },
    { label: 'Angola', value: 'AO' },
    { label: 'Argentina', value: 'AR' },
    { label: 'Armenia', value: 'AM' },
    { label: 'Australia', value: 'AU' },
    { label: 'Austria', value: 'AT' },
    { label: 'Azerbaijan', value: 'AZ' },
    { label: 'Bahamas', value: 'BS' },
    { label: 'Bahrain', value: 'BH' },
    { label: 'Bangladesh', value: 'BD' },
    { label: 'Barbados', value: 'BB' },
    { label: 'Belarus', value: 'BY' },
    { label: 'Belgium', value: 'BE' },
    { label: 'Belize', value: 'BZ' },
    { label: 'Benin', value: 'BJ' },
    { label: 'Bhutan', value: 'BT' },
    { label: 'Bolivia', value: 'BO' },
    { label: 'Bosnia and Herzegovina', value: 'BA' },
    { label: 'Botswana', value: 'BW' },
    { label: 'Brazil', value: 'BR' },
    { label: 'Brunei', value: 'BN' },
    { label: 'Bulgaria', value: 'BG' },
    { label: 'Burkina Faso', value: 'BF' },
    { label: 'Burundi', value: 'BI' },
    { label: 'Cambodia', value: 'KH' },
    { label: 'Cameroon', value: 'CM' },
    { label: 'Canada', value: 'CA' },
    { label: 'Cape Verde', value: 'CV' },
    { label: 'Central African Republic', value: 'CF' },
    { label: 'Chad', value: 'TD' },
    { label: 'Chile', value: 'CL' },
    { label: 'China', value: 'CN' },
    { label: 'Colombia', value: 'CO' },
    { label: 'Comoros', value: 'KM' },
    { label: 'Congo', value: 'CG' },
    { label: 'Costa Rica', value: 'CR' },
    { label: 'Croatia', value: 'HR' },
    { label: 'Cuba', value: 'CU' },
    { label: 'Cyprus', value: 'CY' },
    { label: 'Czech Republic', value: 'CZ' },
    { label: 'Denmark', value: 'DK' },
    { label: 'Djibouti', value: 'DJ' },
    { label: 'Dominica', value: 'DM' },
    { label: 'Dominican Republic', value: 'DO' },
    { label: 'East Timor', value: 'TL' },
    { label: 'Ecuador', value: 'EC' },
    { label: 'Egypt', value: 'EG' },
    { label: 'El Salvador', value: 'SV' },
    { label: 'Equatorial Guinea', value: 'GQ' },
    { label: 'Eritrea', value: 'ER' },
    { label: 'Estonia', value: 'EE' },
    { label: 'Ethiopia', value: 'ET' },
    { label: 'Fiji', value: 'FJ' },
    { label: 'Finland', value: 'FI' },
    { label: 'France', value: 'FR' },
    { label: 'Gabon', value: 'GA' },
    { label: 'Gambia', value: 'GM' },
    { label: 'Georgia', value: 'GE' },
    { label: 'Germany', value: 'DE' },
    { label: 'Ghana', value: 'GH' },
    { label: 'Greece', value: 'GR' },
    { label: 'Grenada', value: 'GD' },
    { label: 'Guatemala', value: 'GT' },
    { label: 'Guinea', value: 'GN' },
    { label: 'Guinea-Bissau', value: 'GW' },
    { label: 'Guyana', value: 'GY' },
    { label: 'Haiti', value: 'HT' },
    { label: 'Honduras', value: 'HN' },
    { label: 'Hungary', value: 'HU' },
    { label: 'Iceland', value: 'IS' },
    { label: 'India', value: 'IN' },
    { label: 'Indonesia', value: 'ID' },
    { label: 'Iran', value: 'IR' },
    { label: 'Iraq', value: 'IQ' },
    { label: 'Ireland', value: 'IE' },
    { label: 'Israel', value: 'IL' },
    { label: 'Italy', value: 'IT' },
    { label: 'Ivory Coast', value: 'CI' },
    { label: 'Jamaica', value: 'JM' },
    { label: 'Japan', value: 'JP' },
    { label: 'Jordan', value: 'JO' },
    { label: 'Kazakhstan', value: 'KZ' },
    { label: 'Kenya', value: 'KE' },
    { label: 'Kiribati', value: 'KI' },
    { label: 'Korea, North', value: 'KP' },
    { label: 'Korea, South', value: 'KR' },
    { label: 'Kosovo', value: 'XK' },
    { label: 'Kuwait', value: 'KW' },
    { label: 'Kyrgyzstan', value: 'KG' },
    { label: 'Laos', value: 'LA' },
    { label: 'Latvia', value: 'LV' },
    { label: 'Lebanon', value: 'LB' },
    { label: 'Lesotho', value: 'LS' },
    { label: 'Liberia', value: 'LR' },
    { label: 'Libya', value: 'LY' },
    { label: 'Liechtenstein', value: 'LI' },
    { label: 'Lithuania', value: 'LT' },
    { label: 'Luxembourg', value: 'LU' },
    { label: 'Macedonia', value: 'MK' },
    { label: 'Madagascar', value: 'MG' },
    { label: 'Malawi', value: 'MW' },
    { label: 'Malaysia', value: 'MY' },
    { label: 'Maldives', value: 'MV' },
    { label: 'Mali', value: 'ML' },
    { label: 'Malta', value: 'MT' },
    { label: 'Marshall Islands', value: 'MH' },
    { label: 'Mauritania', value: 'MR' },
    { label: 'Mauritius', value: 'MU' },
    { label: 'Mexico', value: 'MX' },
    { label: 'Micronesia', value: 'FM' },
    { label: 'Moldova', value: 'MD' },
    { label: 'Monaco', value: 'MC' },
    { label: 'Mongolia', value: 'MN' },
    { label: 'Montenegro', value: 'ME' },
    { label: 'Morocco', value: 'MA' },
    { label: 'Mozambique', value: 'MZ' },
    { label: 'Myanmar', value: 'MM' },
    { label: 'Namibia', value: 'NA' },
    { label: 'Nauru', value: 'NR' },
    { label: 'Nepal', value: 'NP' },
    { label: 'Netherlands', value: 'NL' },
    { label: 'New Zealand', value: 'NZ' },
    { label: 'Nicaragua', value: 'NI' },
    { label: 'Niger', value: 'NE' },
    { label: 'Nigeria', value: 'NG' },
    { label: 'Norway', value: 'NO' },
    { label: 'Oman', value: 'OM' },
    { label: 'Pakistan', value: 'PK' },
    { label: 'Palau', value: 'PW' },
    { label: 'Panama', value: 'PA' },
    { label: 'Papua New Guinea', value: 'PG' },
    { label: 'Paraguay', value: 'PY' },
    { label: 'Peru', value: 'PE' },
    { label: 'Philippines', value: 'PH' },
    { label: 'Poland', value: 'PL' },
    { label: 'Portugal', value: 'PT' },
    { label: 'Qatar', value: 'QA' },
    { label: 'Romania', value: 'RO' },
    { label: 'Russia', value: 'RU' },
    { label: 'Rwanda', value: 'RW' },
    { label: 'Saint Kitts and Nevis', value: 'KN' },
    { label: 'Saint Lucia', value: 'LC' },
    { label: 'Saint Vincent', value: 'VC' },
    { label: 'Samoa', value: 'WS' },
    { label: 'San Marino', value: 'SM' },
    { label: 'Sao Tome and Principe', value: 'ST' },
    { label: 'Saudi Arabia', value: 'SA' },
    { label: 'Senegal', value: 'SN' },
    { label: 'Serbia', value: 'RS' },
    { label: 'Seychelles', value: 'SC' },
    { label: 'Sierra Leone', value: 'SL' },
    { label: 'Singapore', value: 'SG' },
    { label: 'Slovakia', value: 'SK' },
    { label: 'Slovenia', value: 'SI' },
    { label: 'Solomon Islands', value: 'SB' },
    { label: 'Somalia', value: 'SO' },
    { label: 'South Africa', value: 'ZA' },
    { label: 'South Sudan', value: 'SS' },
    { label: 'Spain', value: 'ES' },
    { label: 'Sri Lanka', value: 'LK' },
    { label: 'Sudan', value: 'SD' },
    { label: 'Suriname', value: 'SR' },
    { label: 'Swaziland', value: 'SZ' },
    { label: 'Sweden', value: 'SE' },
    { label: 'Switzerland', value: 'CH' },
    { label: 'Syria', value: 'SY' },
    { label: 'Taiwan', value: 'TW' },
    { label: 'Tajikistan', value: 'TJ' },
    { label: 'Tanzania', value: 'TZ' },
    { label: 'Thailand', value: 'TH' },
    { label: 'Togo', value: 'TG' },
    { label: 'Tonga', value: 'TO' },
    { label: 'Trinidad and Tobago', value: 'TT' },
    { label: 'Tunisia', value: 'TN' },
    { label: 'Turkey', value: 'TR' },
    { label: 'Turkmenistan', value: 'TM' },
    { label: 'Tuvalu', value: 'TV' },
    { label: 'Uganda', value: 'UG' },
    { label: 'Ukraine', value: 'UA' },
    { label: 'United Arab Emirates', value: 'AE' },
    { label: 'United Kingdom', value: 'GB' },
    { label: 'United States', value: 'US' },
    { label: 'Uruguay', value: 'UY' },
    { label: 'Uzbekistan', value: 'UZ' },
    { label: 'Vanuatu', value: 'VU' },
    { label: 'Vatican City', value: 'VA' },
    { label: 'Venezuela', value: 'VE' },
    { label: 'Vietnam', value: 'VN' },
    { label: 'Yemen', value: 'YE' },
    { label: 'Zambia', value: 'ZM' },
    { label: 'Zimbabwe', value: 'ZW' },
];

export const CURRENCIES = [
    { label: 'USD - US Dollar', value: 'USD', symbol: '$' },
    { label: 'EUR - Euro', value: 'EUR', symbol: '€' },
    { label: 'GBP - British Pound', value: 'GBP', symbol: '£' },
    { label: 'JPY - Japanese Yen', value: 'JPY', symbol: '¥' },
    { label: 'INR - Indian Rupee', value: 'INR', symbol: '₹' },
    { label: 'LKR - Sri Lankan Rupee', value: 'LKR', symbol: 'Rs' },
    { label: 'AUD - Australian Dollar', value: 'AUD', symbol: 'A$' },
    { label: 'CAD - Canadian Dollar', value: 'CAD', symbol: 'C$' },
    { label: 'CHF - Swiss Franc', value: 'CHF', symbol: 'Fr' },
    { label: 'CNY - Chinese Yuan', value: 'CNY', symbol: '¥' },
    { label: 'NZD - New Zealand Dollar', value: 'NZD', symbol: 'NZ$' },
    { label: 'SGD - Singapore Dollar', value: 'SGD', symbol: 'S$' },
    { label: 'HKD - Hong Kong Dollar', value: 'HKD', symbol: 'HK$' },
    { label: 'SEK - Swedish Krona', value: 'SEK', symbol: 'kr' },
    { label: 'KRW - South Korean Won', value: 'KRW', symbol: '₩' },
    { label: 'BRL - Brazilian Real', value: 'BRL', symbol: 'R$' },
    { label: 'RUB - Russian Ruble', value: 'RUB', symbol: '₽' },
    { label: 'ZAR - South African Rand', value: 'ZAR', symbol: 'R' },
    { label: 'AED - UAE Dirham', value: 'AED', symbol: 'د.إ' },
    { label: 'SAR - Saudi Riyal', value: 'SAR', symbol: '﷼' },
    { label: 'KWD - Kuwaiti Dinar', value: 'KWD', symbol: 'د.ك' },
    { label: 'PKR - Pakistani Rupee', value: 'PKR', symbol: 'Rs' },
    { label: 'BDT - Bangladeshi Taka', value: 'BDT', symbol: '৳' },
    { label: 'MYR - Malaysian Ringgit', value: 'MYR', symbol: 'RM' },
    { label: 'THB - Thai Baht', value: 'THB', symbol: '฿' },
    { label: 'IDR - Indonesian Rupiah', value: 'IDR', symbol: 'Rp' },
    { label: 'PHP - Philippine Peso', value: 'PHP', symbol: '₱' },
    { label: 'VND - Vietnamese Dong', value: 'VND', symbol: '₫' },
    { label: 'TRY - Turkish Lira', value: 'TRY', symbol: '₺' },
];

export const getCurrencySymbol = (code) => {
    const currency = CURRENCIES.find(c => c.value === code);
    return currency ? currency.symbol : '$';
};

export const TRANSACTION_CATEGORIES = [
    {
        label: 'Housing 🏠',
        value: 'Housing',
        subCategories: [
            { label: 'Rent / Mortgage', value: 'Rent / Mortgage' },
            { label: 'Electricity', value: 'Electricity' },
            { label: 'Water', value: 'Water' },
            { label: 'Gas', value: 'Gas' },
            { label: 'Internet', value: 'Internet' },
            { label: 'Home Maintenance', value: 'Home Maintenance' },
            { label: 'Furniture & Appliances', value: 'Furniture & Appliances' },
        ]
    },
    {
        label: 'Food & Dining 🍔',
        value: 'Food & Dining',
        subCategories: [
            { label: 'Groceries', value: 'Groceries' },
            { label: 'Restaurants', value: 'Restaurants' },
            { label: 'Fast Food', value: 'Fast Food' },
            { label: 'Coffee / Tea', value: 'Coffee / Tea' },
            { label: 'Snacks', value: 'Snacks' },
        ]
    },
    {
        label: 'Transportation 🚗',
        value: 'Transportation',
        subCategories: [
            { label: 'Fuel / Petrol', value: 'Fuel / Petrol' },
            { label: 'Bus / Train', value: 'Bus / Train' },
            { label: 'Taxi / Ride Sharing', value: 'Taxi / Ride Sharing' },
            { label: 'Vehicle Maintenance', value: 'Vehicle Maintenance' },
            { label: 'Parking Fees', value: 'Parking Fees' },
            { label: 'Vehicle Insurance', value: 'Vehicle Insurance' },
        ]
    },
    {
        label: 'Bills & Utilities 💡',
        value: 'Bills & Utilities',
        subCategories: [
            { label: 'Mobile Phone Bill', value: 'Mobile Phone Bill' },
            { label: 'Internet Bill', value: 'Internet Bill' },
            { label: 'Electricity Bill', value: 'Electricity Bill' },
            { label: 'Water Bill', value: 'Water Bill' },
            { label: 'TV Subscriptions', value: 'TV Subscriptions' },
        ]
    },
    {
        label: 'Shopping 🛍️',
        value: 'Shopping',
        subCategories: [
            { label: 'Clothes', value: 'Clothes' },
            { label: 'Electronics', value: 'Electronics' },
            { label: 'Accessories', value: 'Accessories' },
            { label: 'Household Items', value: 'Household Items' },
            { label: 'Online Purchases', value: 'Online Purchases' },
        ]
    },
    {
        label: 'Health & Medical 🏥',
        value: 'Health & Medical',
        subCategories: [
            { label: 'Doctor Visits', value: 'Doctor Visits' },
            { label: 'Medicine', value: 'Medicine' },
            { label: 'Health Insurance', value: 'Health Insurance' },
            { label: 'Medical Tests', value: 'Medical Tests' },
            { label: 'Fitness / Gym', value: 'Fitness / Gym' },
        ]
    },
    {
        label: 'Education 📚',
        value: 'Education',
        subCategories: [
            { label: 'Tuition Fees', value: 'Tuition Fees' },
            { label: 'Books', value: 'Books' },
            { label: 'Courses', value: 'Courses' },
            { label: 'Stationery', value: 'Stationery' },
            { label: 'Online Learning', value: 'Online Learning' },
        ]
    },
    {
        label: 'Entertainment 🎬',
        value: 'Entertainment',
        subCategories: [
            { label: 'Movies', value: 'Movies' },
            { label: 'Games', value: 'Games' },
            { label: 'Streaming Services', value: 'Streaming Services' },
            { label: 'Concerts / Events', value: 'Concerts / Events' },
            { label: 'Hobbies', value: 'Hobbies' },
        ]
    },
    {
        label: 'Travel ✈️',
        value: 'Travel',
        subCategories: [
            { label: 'Flights', value: 'Flights' },
            { label: 'Hotels', value: 'Hotels' },
            { label: 'Transport during travel', value: 'Transport during travel' },
            { label: 'Travel Insurance', value: 'Travel Insurance' },
            { label: 'Tour Packages', value: 'Tour Packages' },
        ]
    },
    {
        label: 'Personal Care 💇',
        value: 'Personal Care',
        subCategories: [
            { label: 'Haircut', value: 'Haircut' },
            { label: 'Cosmetics', value: 'Cosmetics' },
            { label: 'Skincare', value: 'Skincare' },
            { label: 'Salon', value: 'Salon' },
        ]
    },
    {
        label: 'Financial 💳',
        value: 'Financial',
        subCategories: [
            { label: 'Loan Payments', value: 'Loan Payments' },
            { label: 'Credit Card Payments', value: 'Credit Card Payments' },
            { label: 'Taxes', value: 'Taxes' },
            { label: 'Bank Fees', value: 'Bank Fees' },
        ]
    },
    {
        label: 'Others 📦',
        value: 'Others',
        subCategories: [
            { label: 'Donations / Charity', value: 'Donations / Charity' },
            { label: 'Gifts', value: 'Gifts' },
            { label: 'Miscellaneous', value: 'Miscellaneous' },
        ]
    },
];

export const TRANSACTION_TYPES = [
    { label: 'Expense', value: 'Expense' },
    { label: 'Income', value: 'Income' },
    { label: 'Transfer', value: 'Transfer' },
];
